SERVER_AUTH_SUCCESS = "SUCCESS"
SERVER_AUTH_FAIL = "FAIL"

TYPE_DISCONNECT = "!DISCONNECT"
TYPE_MESSAGE = "!MESSAGE"
TYPE_AUTH = "!AUTH"

TYPE_REGISTER_CENTRAL = "!REG_CENTRAL"
TYPE_LOGIN_CENTRAL = "!LOGIN_CENTRAL"
TYPE_SUCCESS_CENTRAL = "!SUCCESS_CENTRAL"
TYPE_FAIL_CENTRAL = "!FAIL_CENTRAL"

TYPE_ERROR_UNAUTHORIZED = "!UNAUTHORIZED"
