# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DaftarGF.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Masuk(object):
    def setupUi(self, Masuk):
        Masuk.setObjectName("Masuk")
        Masuk.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Masuk)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(340, 330, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 40, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 90, 71, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 160, 131, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 240, 131, 16))
        self.label_4.setObjectName("label_4")
        self.masukanUsn = QtWidgets.QLineEdit(self.centralwidget)
        self.masukanUsn.setGeometry(QtCore.QRect(250, 180, 301, 41))
        self.masukanUsn.setObjectName("masukanUsn")
        self.masukanPsw = QtWidgets.QLineEdit(self.centralwidget)
        self.masukanPsw.setGeometry(QtCore.QRect(250, 260, 301, 41))
        self.masukanPsw.setObjectName("masukanPsw")
        Masuk.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Masuk)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        self.menuRoomChat = QtWidgets.QMenu(self.menubar)
        self.menuRoomChat.setObjectName("menuRoomChat")
        self.menuProfile = QtWidgets.QMenu(self.menubar)
        self.menuProfile.setObjectName("menuProfile")
        Masuk.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Masuk)
        self.statusbar.setObjectName("statusbar")
        Masuk.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuRoomChat.menuAction())
        self.menubar.addAction(self.menuProfile.menuAction())

        self.retranslateUi(Masuk)
        QtCore.QMetaObject.connectSlotsByName(Masuk)

    def retranslateUi(self, Masuk):
        _translate = QtCore.QCoreApplication.translate
        Masuk.setWindowTitle(_translate("Masuk", "MainWindow"))
        self.pushButton.setStatusTip(_translate("Masuk", "Continue to NewRoomCHat"))
        self.pushButton.setText(_translate("Masuk", "Continue"))
        self.label.setText(_translate("Masuk", "Ganyang Fufufafa"))
        self.label_2.setText(_translate("Masuk", "RoomChat"))
        self.label_3.setText(_translate("Masuk", "Username"))
        self.label_4.setText(_translate("Masuk", "Password"))
        self.masukanUsn.setStatusTip(_translate("Masuk", "Masukan Username yang anda inginkan"))
        self.masukanPsw.setStatusTip(_translate("Masuk", "Buat Password"))
        self.menuRoomChat.setTitle(_translate("Masuk", "RoomChat"))
        self.menuProfile.setTitle(_translate("Masuk", "Profile"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Masuk = QtWidgets.QMainWindow()
    ui = Ui_Masuk()
    ui.setupUi(Masuk)
    Masuk.show()
    sys.exit(app.exec_())
