# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'join_roomchat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_JoinRoomchat(object):
    def setupUi(self, JoinRoomchat):
        JoinRoomchat.setObjectName("JoinRoomchat")
        JoinRoomchat.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(JoinRoomchat)
        self.centralwidget.setObjectName("centralwidget")
        self.enterButton = QtWidgets.QPushButton(self.centralwidget)
        self.enterButton.setGeometry(QtCore.QRect(330, 400, 141, 41))
        self.enterButton.setObjectName("enterButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 110, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(250, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.masukanPsw = QtWidgets.QLineEdit(self.centralwidget)
        self.masukanPsw.setGeometry(QtCore.QRect(250, 350, 291, 31))
        self.masukanPsw.setObjectName("masukanPsw")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 80, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.masukanPort = QtWidgets.QLineEdit(self.centralwidget)
        self.masukanPort.setGeometry(QtCore.QRect(250, 270, 291, 31))
        self.masukanPort.setObjectName("masukanPort")
        self.masukanIP = QtWidgets.QLineEdit(self.centralwidget)
        self.masukanIP.setGeometry(QtCore.QRect(250, 190, 291, 31))
        self.masukanIP.setObjectName("masukanIP")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 320, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 240, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        JoinRoomchat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(JoinRoomchat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        JoinRoomchat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(JoinRoomchat)
        self.statusbar.setObjectName("statusbar")
        JoinRoomchat.setStatusBar(self.statusbar)

        self.retranslateUi(JoinRoomchat)
        QtCore.QMetaObject.connectSlotsByName(JoinRoomchat)

    def retranslateUi(self, JoinRoomchat):
        _translate = QtCore.QCoreApplication.translate
        JoinRoomchat.setWindowTitle(_translate("JoinRoomchat", "MainWindow"))
        self.enterButton.setStatusTip(_translate("JoinRoomchat", "Masuk ke RoomChat"))
        self.enterButton.setText(_translate("JoinRoomchat", "Enter"))
        self.label_2.setText(_translate("JoinRoomchat", "Roomchat"))
        self.label_4.setText(_translate("JoinRoomchat", "IP Address"))
        self.masukanPsw.setStatusTip(_translate("JoinRoomchat", "Masukan password roomchat"))
        self.label.setText(_translate("JoinRoomchat", "Join"))
        self.masukanPort.setStatusTip(_translate("JoinRoomchat", "Masukan Nomor Port"))
        self.masukanIP.setStatusTip(_translate("JoinRoomchat", "Masukan IP address"))
        self.label_6.setText(_translate("JoinRoomchat", "Password Roomchat"))
        self.label_5.setText(_translate("JoinRoomchat", "Port Number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    JoinRoomchat = QtWidgets.QMainWindow()
    ui = Ui_JoinRoomchat()
    ui.setupUi(JoinRoomchat)
    JoinRoomchat.show()
    sys.exit(app.exec_())
