# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RoomChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Roomchat(object):
    def setupUi(self, Roomchat):
        Roomchat.setObjectName("Roomchat")
        Roomchat.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Roomchat)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 70, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 40, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.MessagePanel = QtWidgets.QTextEdit(self.centralwidget)
        self.MessagePanel.setGeometry(QtCore.QRect(60, 120, 671, 321))
        self.MessagePanel.setObjectName("MessagePanel")
        self.MessageBox = QtWidgets.QLineEdit(self.centralwidget)
        self.MessageBox.setGeometry(QtCore.QRect(60, 450, 551, 41))
        self.MessageBox.setObjectName("MessageBox")
        self.SendButton = QtWidgets.QPushButton(self.centralwidget)
        self.SendButton.setGeometry(QtCore.QRect(620, 450, 111, 41))
        self.SendButton.setObjectName("SendButton")
        self.returnHome = QtWidgets.QPushButton(self.centralwidget)
        self.returnHome.setGeometry(QtCore.QRect(60, 90, 81, 31))
        self.returnHome.setObjectName("returnHome")
        Roomchat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Roomchat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        Roomchat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Roomchat)
        self.statusbar.setObjectName("statusbar")
        Roomchat.setStatusBar(self.statusbar)

        self.retranslateUi(Roomchat)
        QtCore.QMetaObject.connectSlotsByName(Roomchat)

    def retranslateUi(self, Roomchat):
        _translate = QtCore.QCoreApplication.translate
        Roomchat.setWindowTitle(_translate("Roomchat", "MainWindow"))
        self.label_3.setText(_translate("Roomchat", "Roomchat"))
        self.label.setText(_translate("Roomchat", "GanyangFufufafa"))
        self.MessageBox.setStatusTip(_translate("Roomchat", "Tuliskan Pesan"))
        self.SendButton.setStatusTip(_translate("Roomchat", "Kirim Pesan"))
        self.SendButton.setText(_translate("Roomchat", "Send"))
        self.returnHome.setStatusTip(_translate("Roomchat", "Keluar"))
        self.returnHome.setText(_translate("Roomchat", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Roomchat = QtWidgets.QMainWindow()
    ui = Ui_Roomchat()
    ui.setupUi(Roomchat)
    Roomchat.show()
    sys.exit(app.exec_())
